import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/Navigation";
import { Inter } from "next/font/google";
import { getRandomPokemonName } from "@/util/pokemons";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const r1 = getRandomPokemonName();
  const r2 = getRandomPokemonName(r1);

  return (
    <html className={inter.className} lang="en">
      <body>
        <Navigation randomR1={r1} randomR2={r2} />
        {children}
      </body>
    </html>
  );
}
